/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.krystianrymonlipinski.main_frame;

import com.krystianrymonlipinski.algorithm.MainAlgorithm;
import com.krystianrymonlipinski.tree.model.Tree;
import draughts.library.managers.BoardManager;

import javax.swing.*;

public class MainFrame {

    JFrame mainFrame;
    JButton newGameButton;
    JButton makeMoveButton;
    JButton loadMoveButton;

    public static void main(String[] args) {
        new MainFrame().createFrame();

    }

    private void createFrame() {
        mainFrame = new JFrame();
        mainFrame.setSize(900, 700);
        mainFrame.setVisible(true);
        mainFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
}
