/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.krystianrymonlipinski;

import com.krystianrymonlipinski.main_frame.MainFrame;
import org.junit.Test;
import static org.junit.Assert.*;

public class MainFrameTest {
    @Test public void testAppHasAGreeting() {
        MainFrame classUnderTest = new MainFrame();
    }
}
